"""Create exercises, workouts, and workout_exercises tables

Revision ID: 67dd6b2a1ede
Revises: 
Create Date: 2026-08-01 17:52:49.763946

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '67dd6b2a1ede'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=80), nullable=False),
    sa.Column('category', sa.String(length=40), nullable=False),
    sa.Column('equipment_needed', sa.Boolean(), nullable=False),
    sa.CheckConstraint("category IN ('strength', 'cardio', 'mobility', 'balance', 'core')", name=op.f('ck_exercises_category_allowed')),
    sa.CheckConstraint('length(trim(name)) >= 2', name=op.f('ck_exercises_name_min_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_exercises')),
    sa.UniqueConstraint('name', name='uq_exercises_name'),
    sa.UniqueConstraint('name', name=op.f('uq_exercises_name'))
    )
    op.create_table('workouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=False),
    sa.Column('duration_minutes', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.CheckConstraint('duration_minutes > 0 AND duration_minutes <= 300', name=op.f('ck_workouts_duration_minutes_range')),
    sa.CheckConstraint('notes IS NULL OR length(notes) <= 500', name=op.f('ck_workouts_notes_length')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workouts'))
    )
    op.create_table('workout_exercises',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('workout_id', sa.Integer(), nullable=False),
    sa.Column('exercise_id', sa.Integer(), nullable=False),
    sa.Column('reps', sa.Integer(), nullable=True),
    sa.Column('sets', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.CheckConstraint('(reps IS NOT NULL AND sets IS NOT NULL) OR duration_seconds IS NOT NULL', name=op.f('ck_workout_exercises_reps_sets_or_duration_required')),
    sa.CheckConstraint('duration_seconds IS NULL OR duration_seconds > 0', name=op.f('ck_workout_exercises_duration_seconds_positive')),
    sa.CheckConstraint('reps IS NULL OR reps > 0', name=op.f('ck_workout_exercises_reps_positive')),
    sa.CheckConstraint('sets IS NULL OR sets > 0', name=op.f('ck_workout_exercises_sets_positive')),
    sa.ForeignKeyConstraint(['exercise_id'], ['exercises.id'], name=op.f('fk_workout_exercises_exercise_id_exercises'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['workout_id'], ['workouts.id'], name=op.f('fk_workout_exercises_workout_id_workouts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_workout_exercises')),
    sa.UniqueConstraint('workout_id', 'exercise_id', name='uq_workout_exercises_workout_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('workout_exercises')
    op.drop_table('workouts')
    op.drop_table('exercises')
    # ### end Alembic commands ###
